SEED_URLS = [
    # Product Categories (13)
    "https://myklaticrete.com/products/tile-adhesive/",
    "https://myklaticrete.com/products/specialty-adhesive/",
    "https://myklaticrete.com/products/stone-adhesives/",
    "https://myklaticrete.com/products/epoxy-tile-grout/",
    "https://myklaticrete.com/products/waterproofing/",
    "https://myklaticrete.com/products/tile-and-stone-care/",
    "https://myklaticrete.com/products/cleaning-solutions/",
    "https://myklaticrete.com/products/screed-concrete/",
    "https://myklaticrete.com/products/sound-control/",
    "https://myklaticrete.com/products/aac-block-adhesive/",
    "https://myklaticrete.com/products/3-d-printing-mortar/",
    "https://myklaticrete.com/products/cement-additive/",
    "https://myklaticrete.com/products/application-tools/",
    # Individual Products - Tile Adhesives (10)
    "https://myklaticrete.com/products/tile-adhesive/thin-set-adhesives/myk-latafix-305/",
    "https://myklaticrete.com/products/tile-adhesive/polymer-modified-thin-set-adhesives/myk-laticrete-325-high-flex/",
    "https://myklaticrete.com/products/tile-adhesive/polymer-modified-thin-set-adhesives/myk-laticrete-335-maxi/",
    "https://myklaticrete.com/products/tile-adhesive/polymer-modified-thin-set-adhesives/myk-laticrete-335-super-flex/",
    "https://myklaticrete.com/products/tile-adhesive/polymer-modified-thin-set-adhesives/myk-laticrete-345-super-flex/",
    "https://myklaticrete.com/products/tile-adhesive/thin-set-adhesives/myk-laticrete-307/",
    "https://myklaticrete.com/products/tile-adhesive/thin-set-adhesives/myk-laticrete-315-plus/",
    "https://myklaticrete.com/products/tile-adhesive/latex-fortified-thin-set-adhesives/myk-laticrete-111-4237/",
    "https://myklaticrete.com/products/tile-adhesive/latex-fortified-thin-set-adhesives/myk-laticrete-111-73/",
    "https://myklaticrete.com/products/tile-adhesive/polymer-based-adhesives/myk-laticrete-303/",
    # Specialty Adhesives (8)
    "https://myklaticrete.com/products/specialty-adhesive/myk-laticrete-dwa-215-plus/",
    "https://myklaticrete.com/products/specialty-adhesive/myk-laticrete-latapoxy-310/",
    "https://myklaticrete.com/products/specialty-adhesive/latapoxy-300/",
    "https://myklaticrete.com/products/specialty-adhesive/myk-laticrete-pua-212/",
    "https://myklaticrete.com/products/specialty-adhesive/latapoxy-fast-and-clear/",
    "https://myklaticrete.com/products/specialty-adhesive/myk-laticrete-dwa-215/",
    "https://myklaticrete.com/products/specialty-adhesive/latapoxy-standard/",
    "https://myklaticrete.com/products/specialty-adhesive/latapoxy-270/",
    # Stone (2), Grouts (7), Waterproofing (2)
    "https://myklaticrete.com/products/stone-adhesives/myk-laticrete-340-medium-bed-adhesive/",
    "https://myklaticrete.com/products/stone-adhesives/myk-laticrete-320-thick-bed-adhesive/",
    "https://myklaticrete.com/products/epoxy-tile-grout/stainfree/myk-laticrete-sp-100-tile-joint/",
    "https://myklaticrete.com/products/epoxy-tile-grout/stainfree/myk-laticrete-sp-100-duo/",
    "https://myklaticrete.com/products/epoxy-tile-grout/stainfree/myk-laticrete-sp-100-uno/",
    "https://myklaticrete.com/products/epoxy-tile-grout/stainfree/myk-laticrete-stellar-grout/",
    "https://myklaticrete.com/products/epoxy-tile-grout/cementitious/myk-laticrete-500/",
    "https://myklaticrete.com/products/epoxy-tile-grout/cementitious/myk-laticrete-600/",
    "https://myklaticrete.com/products/epoxy-tile-grout/specialty-grout/latapoxy-2000/",
    "https://myklaticrete.com/products/waterproofing/laticrete-9237/",
    "https://myklaticrete.com/products/waterproofing/myk-laticrete-hydro-ban/",
    # Downloads (TDS/MSDS)
    "https://myklaticrete.com/downloads/tds/",
    "https://myklaticrete.com/downloads/msds/",
    "https://myklaticrete.com/downloads/leaflets-brochure/",
    "https://myklaticrete.com/downloads/specifications/",
    "https://myklaticrete.com/downloads/product-catalogue/",
    # Solutions/Challenges
    "https://myklaticrete.com/solutions-by-applications/swimming-pools/",
    "https://myklaticrete.com/challenges-and-solutions/leaking-bathrooms/",
    "https://myklaticrete.com/challenges-and-solutions/tiles-on-different-substrates/",
    "https://myklaticrete.com/challenges-and-solutions/stones-tiles-fixing-on-external-facade/",
    "https://myklaticrete.com/challenges-and-solutions/laying-new-tiles-on-old-tiles/",
    # Technical Blogs
    "https://myklaticrete.com/blog/tile-adhesives-vs-cement/",
    "https://myklaticrete.com/blog/cold-weather-tiling-and-grouting/",
    "https://myklaticrete.com/blog/surface-preparation-tips-for-hot-weather-tiling/",
]
